spring:
  application:
    name: notification
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VHOST:guest}
    connection-timeout: 30000
    exchange:
      name: order.exchange
    queue:
      name: order.queue
    routing:
      key: order.tracking
server:
  port: 8084