spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VHOST:guest}
    connection-timeout: 30000
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    tracing:
      sampling:
        probability: 1.0
  data:
    mongodb:
      uri: ${DB_URL}
      database: ${DB_NAME}
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: ujwal
#    password: ujwal
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database: postgresql


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7