spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VHOST:guest}
    connection-timeout: 30000
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\Microservices\Ecommerce\configserver\src\main\resources\config

server:
  port: 8888
